server {
    listen 80;                       # escuta na porta 80 dentro do container
    root /usr/share/nginx/html;      # pasta onde estão os arquivos do build
    index index.html;                # arquivo inicial

    location / {                     # vale para qualquer endereço
        try_files $uri $uri/ /index.html;
    }
}